version: '3.8'

services:
  reverse-proxy:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - proxy-network
    depends_on:
      - service1
      - service2
      - service3

  service1:
    build: 
      context: ./examples/test-services
      dockerfile: Dockerfile.service
    environment:
      - PORT=3001
      - SERVICE_NAME=service1
    networks:
      - proxy-network
    command: ["node", "service1.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  service2:
    build:
      context: ./examples/test-services
      dockerfile: Dockerfile.service
    environment:
      - PORT=3002
      - SERVICE_NAME=service2
    networks:
      - proxy-network
    command: ["node", "service2.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  service3:
    build:
      context: ./examples/test-services
      dockerfile: Dockerfile.service
    environment:
      - PORT=3003
      - SERVICE_NAME=service3
    networks:
      - proxy-network
    command: ["node", "service3.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy-network:
    driver: bridge