services:
  reverse-proxy:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - proxy-network
    depends_on:
      - prometheus
      - service1
      - service2
      - service3

  service1:
    build: 
      context: ./examples/test-services
      dockerfile: Dockerfile.service
    environment:
      - PORT=3001
      - SERVICE_NAME=service1
    networks:
      - proxy-network
    deploy:
      replicas: 2

  service2:
    build: 
      context: ./examples/test-services
      dockerfile: Dockerfile.service
    environment:
      - PORT=3002
      - SERVICE_NAME=service2
    networks:
      - proxy-network
    deploy:
      replicas: 2

  service3:
    build: 
      context: ./examples/test-services
      dockerfile: Dockerfile.service
    environment:
      - PORT=3003
      - SERVICE_NAME=service3
    networks:
      - proxy-network
    deploy:
      replicas: 2

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/config/prometheus:/etc/prometheus  
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  prometheus_data: